### ISSUE TITLE
ee_install_set_pyenv: error when py_env=NULL?

### ISSUE THREAD

**Issue by MatthieuStigler** [r-spatial/rgee#118]
* rgee version: 1.0.8

It seems like `ee_install_set_pyenv()` will return an error if the argument `py_env` is left NULL? I get `object 'ret_env' not found` which seems to arise since there is only a check `if (!is.null(py_env))` but no action if it is kept NULL? 

What should be the default behaviour of `ee_install_set_pyenv()` when no `py_env` value is given by the user? Maybe it would be worth to return an explicit error message like: *please provide a value for py_env*?

**Comment by csaybar** [comment]
Hi @MatthieuStigler  thanks for pointing it out!. We will add this feature soon. **rgee** needs a Python env, to make the function `ee_install_upgrade`  works. Although is not a good solution, the next code would help:

```r
ee_install_set_pyenv(py_path = "/usr/bin/python3", py_env = "foo") #no matter the name of py_env 
```
Remember that the Python PATH you choose should have **earthengine-api** Python package installed. 

Let us know if you have problems setting rgee Python dependencies!

**Comment by MatthieuStigler** [comment]
Thanks Cesar! 

So if I have a conda environment called `ee` (which I wold normally use with: `conda activate ee`), do I just need to do:

`rgee::ee_install_set_pyenv(py_path = "~/Programs/anaconda3/envs/ee/bin/python", py_env = "ee")`

myabe it would be nice to also add 1-2 examples in the help file of `ee_install_set_pyenv`, with a `\dontrun{}`? 

Thanks!!

**Comment by csaybar** [comment]
Hi @MatthieuStigler the bug was fixed and add extra documentation in the [installation section](https://github.com/r-spatial/rgee#installation). 

```r
library(remotes)
install_github("r-spatial/rgee")
```

 We need to make some extra changes in the install module to permit add examples because if we add it right now it will break our testing pipeline in GH. 

But indeed the examples will be in the next release of rgee :), thanks for the recommendation!. I will close the issue but feel free to open it again if you continue having problems with ee_install_set_pyenv.
