### ISSUE TITLE
How can I to get all bands in an image to the same resolution size ? 

### ISSUE THREAD

**Issue by ambarja** [r-spatial/rgee#145]
Hi @csaybar in the moment I'm tying to create a new dataset with different variables and my question is the How can I to get all bands with the same size resolution?

In stackoverflow I fond an issue similar [issue](https://gis.stackexchange.com/questions/316596/how-can-i-resample-a-image-or-imagecollection-to-a-higher-resolution-in-google-e)

* rgee version: 1.0.8
* R version: 4.0.2
* Operating System: Pop Os

```r
library(rgee)
ee_Initialize()
```
```r
> ee_Initialize()
── rgee 1.0.8 ────────────────────────────────────────────── earthengine-api 0.1.259 ── 
 ✓ email: not_defined
 ✓ Initializing Google Earth Engine:  DONE!
 ✓ Earth Engine user: users/antonybarja8 
─────────────────────────────────────────────────────────────────────────
```

#### Landcover 
```r
imp  <-  ee$ImageCollection("USGS/NLCD_RELEASES/2016_REL")$
  filter(ee$Filter$calendarRange(2016,2016,'year'))$
  select('impervious')$ 
  first()$
  rename("imp")

imp$projection()$nominalScale()$getInfo() # 30m
``` 

```r
> imp$projection()$nominalScale()$getInfo()
[1] 30
```
#### Temperature
```r
tmax <- ee$ImageCollection("MODIS/006/MOD11A1")$
  select("LST_Day_1km")$
  filter(ee$Filter$calendarRange(2016,2016,'year'))$
  max()$
  multiply(0.02)$
  rename('max')
tmax$projection()$nominalScale()$getInfo() #111319.5
```
```r
> tmax$projection()$nominalScale()$getInfo()
[1] 111319.5
```

#### Creation of dataset
```r
dataset <- ee$Image(c(imp,tmax))
dataset$projection()$nominalScale()$getInfo()
```
```r
Error in py_call_impl(callable, dots$args, dots$keywords) : 
EEException: Image.projection: The bands of the specified image contains different projections.
Use Image.select to pick a single band. 
```

**Comment by jdbcode** [comment]
You can set all bands to a specified scale and crs using [`reproject`](https://developers.google.com/earth-engine/guides/projections#reprojecting). Consider the [resampling](https://developers.google.com/earth-engine/guides/resample#resampling) method when you apply it.

Note that often reprojecting is not necessary though because most exporting and analysis functions like reductions provide `scale` and `crs` params which will handling reprojecting to a specified scale (see [scale of analysis](https://developers.google.com/earth-engine/guides/scale#scale-of-analysis)).

Also see [`reduceResolution`](https://developers.google.com/earth-engine/guides/resample#reduce-resolution) for more control over the statistic for situations where you reduce scale of one band/image to match another.

**Comment by ambarja** [comment]
Thanks @jdbcode  , recently I created a function with reproject and  scale,  afther it was applied to dataset with the bands of size different , now the output have 30 meters.
Is this correct ? :thinking: 
**This is my code:**

```r
# Resampling image
resample_size <- function(x){
  reduce_size <- x$reproject(
    crs = imp$projection(),
    scale = 30
  )
  return(reduce_size)
}
```
```r
dataset <- ee$Image(c(imp,tmax)) %>% resample_size()
dataset$projection()$nominalScale()$getInfo()
```
```r
> dataset$projection()$nominalScale()$getInfo()
[1] 30
````

**Comment by csaybar** [comment]
Just a curious, why do you need to rescale all the bands to the same spatial resolution? : 3

**Comment by ambarja** [comment]
Excellent question, I want to create an environmental index using a PCA with Modis and Landsat data.

**Comment by csaybar** [comment]
As @jdbcode comment you don't need to change the scale, See [https://developers.google.com/earth-engine/guides/scale](https://developers.google.com/earth-engine/guides/scale)

**Comment by ambarja** [comment]
I nderstand, I thought it was necessary to have aligned each pixel with the same resolution, thank you very much for the answer and the comments, I promise to read your references. :nerd_face:
