### ISSUE TITLE
Question - rgee inspector tool functionality available?

### ISSUE THREAD

**Issue by zackarno** [r-spatial/rgee#217]
Hello,

I was wondering if `rgee` has functionality to use an inspector tool on map visualizations (similar to the Javascript code editor)?  If not, is there a known work-around or is this a feasible enhancement/feature request?

**Comment by csaybar** [comment]
This would be a very useful feature, however, I haven't had the time to implement it. In order to minimize dependencies on rgee, I think this would fit better in another R package (maybe eeProfiler?). We don't need to start from scratch, since much of the **[mapedit](https://github.com/r-spatial/mapedit)** code could be reused.

I'm going to leave this issue open in case someone is interested in implementing it.

**Comment by zackarno** [comment]
@csaybar  & @ambarja  - was looking into this possibility. I saw that @ambarja had started the [rgeeInspector](https://github.com/r-earthengine/rgeeInspector) (nice!) .

I opened an issue/question on the leaflet github repo to see if it was possibly to extract the input data object from a leaflet map object (like that created by `rgee::Map$addLayer()`). It seems like it might not be possible because it doesn't seem like leaflet stores the input object in the map object - however it seems possible with {mapview}.

on the issue @tim-salabim had some helpful suggestions : https://github.com/rstudio/leaflet/issues/813#issuecomment-1210512755 .
