### ISSUE TITLE
ee.Algorithms.Image.* available in rgee?

### ISSUE THREAD

**Issue by aloboa** [r-spatial/rgee#244]
Are ee.Algorithms.Image.Segmentation.* tools available through rgee? In particular, ee.Algorithms.Image.Segmentation.* ?

**Comment by aloboa** [comment]
Great!
In order to avoid asking this type of question again, could either
`ee_help(ee$Algorithms$Image) `or `ee_help(ee$Algorithms) `provide a really helpful information?
Or from the ee entry in the Documentation for the package (help(rgee), the selecting ee)
Or perhaps there is another way to get this information that I've not been able to find (apologies in this case).

**Comment by csaybar** [comment]
Hi @aloboa 

what `ee_help` does is render in an R-friendly format the documentation of the [earthengine-api](https://github.com/google/earthengine-api/tree/master/python) Python package. There is no relevant information in `ee$Algorithms$Image` because there is no relevant information in the `ee.Algorithms.Image` Python class.

See the next link: https://github.com/google/earthengine-api/blob/6001b1b120dae417e5d0610ce4edfd29290c5679/python/ee/__init__.py#L57

We have a Rstudio-addin to display the documentation just by pressing F3. https://r-earthengine.com/rgeebook/earth-engine-in-rstudio.html#gee-api-reference-documentation
