### ISSUE TITLE
Question: Continue after the task is disconnected

### ISSUE THREAD

**Issue by TianyaImpression** [r-spatial/rgee#250]
* rgee version: rgee1.1.3
* R version: 4.1.3
* Operating System: win10

![image](https://user-images.githubusercontent.com/22004043/160075727-d328c1c0-fa20-41df-b18a-989ebba8f08a.png)

Sometimes due to poor network, rgee's ee_as_raster task will be interrupted. Is there a way to make it continue to execute after it is interrupted? instead of running again?

Thank you for your reply!

**Comment by csaybar** [comment]
Hi @TianyaImpression, yes I highly recommend always using `lazy=TRUE` in case of poor internet connection. When 'lazy=TRUE', instead of getting a RasterStack object, it will retrieve a 'future::sequential' object.

For instance: 

```r
img_03 <- ee_as_raster(
 image = img,
 region = geometry,
 container = "rgee_dev",
 lazy = TRUE,
 via = "gcs"
)
```

The function above will create a `future::sequential` object with the EE task initialized (i.e. from GEE to DRIVE/GCS). Now using:

```r
img_02_result <- img_02 %>% ee_utils_future_value()
```

Users can decide when exporting the results (from DRIVE/GCS to local). I see that your task was running for a long time, idk the context, but maybe would be better to create small chunks to avoid very long waits.

**Comment by TianyaImpression** [comment]
@csaybar Thank you for your reply! I use GEE to obtain a large range of Landsat images, so the stitching is very time-consuming, and the general processing process will not be interrupted, but the process of rgee Moving image from Google Drive to Local is sometimes interrupted due to the influence of the network. I would like to know this rgee from the Internet Can the process of downloading data from disk be resumed? I am currently downloading manually from the Google Drive
