### ISSUE TITLE
JOSS Review

### ISSUE THREAD

**Issue by gena** [r-spatial/rgee#72]
This is a very nice R package @csaybar and will be for sure useful among R users for geospatial processing combining local analysis with the Cloud-based Google Earth Engine (GEE) processing. 

I've followed instructions provided in the ```README.md``` - everything went smoothly and installed without issues on Windows 10. 

* The second [example](https://github.com/r-spatial/rgee#2-extract-precipitation-values) mentions ```shape/nc.shp``` file, but there is no link to where the file can be downloaded - please share it somewhere or add to the repository if it's tiny. This would help users to follow instructions and reproduce your examples 100%. The same is also true for the shp/arequipa.shp in the [second example](https://github.com/r-spatial/rgee#3-create-an-ndvi-animation-js-version).

The documentation on the GitHub is very informative and useful and helps to get started fast with the package.

**Comment by csaybar** [comment]
Hi @gena thank you so much for taking your time in review rgee. With respect to your question, we use the `system.file` function to create reproducible examples, this function helps to retrieve the full file names of files in R packages installed. When a package is installed, everything in [inst/](https://github.com/r-spatial/rgee/tree/master/inst) folder is copied into the top-level package directory (see R code below). We take advance of this and save a toy shapefile [inst/shp](https://github.com/r-spatial/rgee/tree/master/inst/shp) to create reproducible examples and run unit tests.

``` r
list.files(system.file("", package = "rgee"))
#>  [1] "CITATION"    "DESCRIPTION" "help"        "html"        "INDEX"      
#>  [6] "Meta"        "NAMESPACE"   "NEWS.md"     "python"      "R"          
#> [11] "shp"         "tests"       "WORDLIST"
```
<sup>Created on 2020-07-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I think the problem here is that sf is maybe not installed (we use its inst/ files in example 2), we add extra info in the README.rd file for users to take into account that to run example 2 sf must be installed. Please let me know if the problem persists. I will keep #72 open until all the review process was completed.

Have a good Sunday!

**Comment by gena** [comment]
You're right, I could reproduce the example perfectly, thanks for clarifying this!

**Comment by csaybar** [comment]
Hi @gena to move towards rgee acceptance (openjournals/joss-reviews#2272), could we close the issue now?
